name: CI
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install deps
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: yarn install
      - name: Run lint
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: yarn lint
