name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install deps
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cmd: install
      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cmd: test --ci --coverage --maxWorkers=2
